source/accounts/urls.py
from django.urls import path
from accounts.views import login_view, logout_view

app_name = 'accounts'

urlpatterns = [
    path('login', login_view, name='login'),
    path('logout', logout_view, name='logout')
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('webapp.urls', namespace='webapp')),
    path('auth', include('accounts.urls', namespace="accounts"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views import PostDetailView, PostListView, PostCreateView, PostUpdateView, PostDeleteView, UserListView, UserDetailView, UserUpdateView

app_name = 'webapp'

urlpatterns = [
    path('post/<int:pk>', PostDetailView.as_view(), name='post_details'),
    path('', PostListView.as_view(), name='posts'),
    path('post/create', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
    path('users', UserListView.as_view(), name='users'),
    path('user/<int:pk>', UserDetailView.as_view(), name='user_details'),
    path('user/<int:pk>/update', UserUpdateView.as_view(), name='user_update'),
]

source/accounts/models.py
from django.db import models

# Create your models here.

source/webapp/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

# Create your models here.


class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT, related_name='UserInfo', verbose_name="Пользователь")
    phone = models.CharField(max_length=50, verbose_name="Телефон")
    photo = models.ImageField(null=True, blank=True, verbose_name='Фотография')
    friends = models.ManyToManyField(User, blank=True, null=True, related_name="my_friends", verbose_name="Друзья")

    def __str__(self):
        return self.user.get_full_name()


class Post(models.Model):
    title = models.CharField(max_length=50, verbose_name="Заголовок")
    text = models.TextField(max_length=5000, verbose_name="Текст")
    date = models.DateTimeField(default=datetime.now, verbose_name='Дата')
    author = models.ForeignKey(User, on_delete=models.PROTECT, related_name='posts_by_user', verbose_name='Автор')

    def __str__(self):
        return self.title

source/webapp/forms.py
from django import forms
from webapp.models import User, UserInfo, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude =['author', 'date']

class UserForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ['phone', 'photo']

source/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate


def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is None:
            context = {
                'username': username,
                'password': password,
                'has_error': True
            }
            return render(request, 'login.html', context=context)
        else:
            login(request, user=user)
            return redirect('webapp:posts')

    return render(request, 'login.html')


def logout_view(request):
    logout(request)
    return redirect('accounts:login')

source/webapp/views.py
from django.shortcuts import render
from webapp.models import User, UserInfo, Post
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from webapp.forms import PostForm, UserForm
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect

class PostDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'


class PostListView(ListView):
    model = Post
    template_name = 'post_list.html'

    def get_queryset(self):
        return self.model.objects.order_by('-date')

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'post_create.html'
    form_class = PostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:post_details', kwargs={'pk': self.object.pk})


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'post_update.html'
    form_class = PostForm

    def get(self, request, pk):
        user = get_object_or_404(Post, pk=pk)
        if user.pk != self.request.user:
            return HttpResponseRedirect(reverse('webapp:user_details', kwargs={'pk': pk}))
        return super().get(request, pk=pk)

    def get_success_url(self):
        return reverse('webapp:post_details', kwargs={'pk': self.object.pk})

class PostDeleteView(DeleteView):
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('webapp:posts')

    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        if post.author != self.request.user:
            return HttpResponseRedirect(reverse('webapp:post_details', kwargs={'pk': pk}))
        return super().get(request, pk=pk)


class UserDetailView(DetailView):
    model = UserInfo
    template_name = "user_details.html"

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        context['posts'] = self.object.user.posts_by_user.all().order_by('-date')
        return context



class UserListView(ListView):
    model = UserInfo
    template_name = 'user_list.html'


class UserUpdateView(UpdateView):
    model = UserInfo
    template_name = 'user_update.html'
    form_class = UserForm

    def get_success_url(self):
        return reverse('webapp:user_details', kwargs={'pk': self.object.pk})

    def get(self, request, pk):
        user = get_object_or_404(Post, pk=pk)
        if user.pk != self.request.user:
            return HttpResponseRedirect(reverse('webapp:user_details', kwargs={'pk': pk}))
        return super().get(request, pk=pk)

source/accounts/templates/login.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <title>Вход</title>
</head>
<body>
<div class="container">
    <h1 class="text-center">Вход</h1>
    <form action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {% if has_error %}
            <p class="form-text text-danger text-center">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <input type="hidden" name="next" value="{{ next }}">
        <div class="form-row form-group">
            <label for="username" class="col-2 form-text">Имя пользователя:</label>
            <input type="text" class="form-control col-10" name="username" id="username" value="{{ username }}">
        </div>
        <div class="form-row form-group">
            <label for="password" class="col-2 form-text">Пароль:</label>
            <input type="password" class="form-control col-10" name="password" id="password" value="{{ password }}">
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Войти</button>
        </div>
    </form>
</div>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% block styles %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li>
                    <a href="{% url 'webapp:posts' %}" class="nav-link">Главная</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'webapp:users' %}" class="nav-link">Список пользователей</a>
                </li>
            {% if request.user.is_authenticated %}
                 <li class="nav-item">
                <a href="{% url 'webapp:post_create' %}" class="nav-link">Написать пост</a>
                </li>
                 <li class="nav-item">
                <a href="{% url 'webapp:user_update' request.user.pk %}" class="nav-link">Личный кабинет</a>
                </li>
           {% endif %}
            {% block menu %}{% endblock %}
        </ul>
        <form class="form-inline my-2 my-lg-0">
            {% if request.user.is_authenticated %}
                <span class="nav-item navbar-text">Привет, {{ request.user.username }}!</span>
                <a href="{% url 'accounts:logout' %}" class="nav-link">Выход</a>
            {% else %}
                <a href="{% url 'accounts:login' %}" class="nav-link">Войти</a>
           {% endif %}
        </form>
    </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

source/webapp/templates/post_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Добавить пост{% endblock %}

{% block content %}
    <form action="{% url 'webapp:post_create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
{% endblock %}

source/webapp/templates/post_delete.html
{% extends 'base.html' %}
{% block title %}Удалить пост{% endblock %}
{% block content %}
    <h1>Удаление поста</h1>
    <h5>Вы уверены, что хотите удалить пост {{ post.title }}?</h5>
    <form action="{% url 'webapp:post_delete' post.pk %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn, btn-primary">Удалить</button>
    </form>
{% endblock %}

source/webapp/templates/post_detail.html
{% extends 'base.html' %}
{% block title %}Пост (ирония){% endblock %}
{% block content %}

    <h3>{{ post.title }}</h3>
    <p>{{ post.text }}</p>
    Автор: {{ post.author }} <br>
    Дата создания: {{ post.date }} <br>
    {% if post.author == request.user %}
    <a href="{% url 'webapp:post_update' post.pk %}" class="nav-link">Редактировать пост</a>
    <a href="{% url 'webapp:post_delete' post.pk %}" class="nav-link">Удалить пост</a>
    {% endif %}
{% endblock %}

source/webapp/templates/post_list.html
{% extends 'base.html' %}
{% block title %}Заказ{% endblock %}
{% block menu %}
{% endblock %}
{% block content %}
    {% for post in post_list %}
        <h3><a href="{% url 'webapp:post_details' post.pk %}">{{ post.title }}</a></h3>
    Автор: {{ post.author }} <br>
    Дата создания: {{ post.date }} <br>
    {% endfor %}
{% endblock %}

source/webapp/templates/post_update.html
{% extends 'base.html' %}

{% block title %}Изменить пост{% endblock %}

{% block content %}
    <h1>Изменить пост</h1>
    <form action="{% url 'webapp:post_update' form.instance.pk %}" method="post" class="form-group" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
{% endblock %}

source/webapp/templates/user_details.html
{% extends 'base.html' %}
{% block title %}Пользователь {% endblock %}
{% block content %}
    <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="{{ userinfo.photo.url }}" alt="user photo"> <br>
      <div class="card-body">
        <h5 class="card-title">{{ userinfo.user }}</h5>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Телефон: <a href="#" id="link">показать телефон</a> <span id="phone">{{ userinfo.phone }}</span><br></li>
            {% if userinfo.user == request.user %}
                <li class="list-group-item"><a href="{% url 'webapp:user_update' user.pk %}" class="nav-link">Редактировать</a></li>
            {% endif %}
      </ul>
      <div class="card-body">
        <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Друзья</a>
            <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Посты</a>
        </div>
    </nav>
        <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                {% for friend in userinfo.friends.all %}
                    {{ friend }}<br>
                {% endfor %}
            </div>
            <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                {% for post in posts.all %}
                    <a href="{% url 'webapp:post_details' post.pk %}">{{ post.title }}</a><br>
                {% endfor %}
            </div>
        </div>
      </div>
    </div>
    {% if userinfo.user == request.user %}
    <a href="{% url 'webapp:user_update' userinfo.user_id %}" class="nav-link">Редактировать</a>
    {% endif %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
    <script>
    $(document).ready(function() {
        $("#phone").hide();
        $("#link").click(function () {
            $("#link").hide();
            $("#phone").show();
        });
    });
    </script>
{% endblock %}

source/webapp/templates/user_list.html
{% extends 'base.html' %}
{% block title %}Пользователи{% endblock %}
{% block menu %}
{% endblock %}
{% block content %}
    <ul class="list-unstyled">
        {% for userinfo in userinfo_list %}
            <li><a href="{% url 'webapp:user_details' userinfo.pk %}">{{ userinfo.user }}</a><br></li>
        {% endfor %}
    </ul>
{% endblock %}

source/webapp/templates/user_update.html
{% extends 'base.html' %}

{% block title %}Изменить пользователя{% endblock %}

{% block content %}
    <h1>Изменить пользователя</h1>
    <form action="{% url 'webapp:user_update' form.instance.pk %}" method="post" class="form-group" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
{% endblock %}